apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: online-reality
  labels: 
    app: online-reality
  annotations: {{ .Values.website.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.website.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: online-reality
              servicePort: http
    - host: "www.{{ .Values.website.ingress.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: online-reality
              servicePort: http
  tls:
    - hosts:
        - {{ .Values.website.ingress.host }}
        - www.onlinereality.xyz
      secretName: online-reality-tls
