apiVersion: v1
kind: Service
metadata:
  labels:
    app: online-reality
  name: online-reality
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: online-reality
  type: ClusterIP
status:
  loadBalancer: {}
